### ISSUE TITLE
Mention more/older refs for the underlying concepts of all methods

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatiotempcv#107]

**Comment by pat-s** [comment]
I've searched again for older refs related to spatiotemporal partitioning.
To me it seems all relevant literature has been cited.

Waiting for @alexanderbrenning to confirm.

## Block / Tiles

AFAICS Wenger and Olden (2012) and Bahn and McGill (2012) are the oldest refs which used a systematic zone splitting for spatial CV. 

*Already cited*

## Buffering / Disc

Brenning 2005 excluded parts of the training data which were nearer to the test data than the range of the correlogram, essentially following the heuristics of the `spcv_disc` method.

Le Rest 2014 proposed spatial LOOCV.

*Already cited*

## Env blocking

New idea by Valavi et al. directly / {blockCV}.

*Already cited*

## Predefined grouping

Hard to find old literature because there were no clear terms used before ~ 2010 when a specific group of observations was left out (whether spatial or not). Meyer 2018 gave it a distinct name with "Leave-location-out" (LLO) whereas `sperrorest::partition_factor()` was not officially following a named "method". 

## Other languages

See #133

**Comment by alexanderbrenning** [comment]
- **Predefined grouping** is not a very precise concept, as it may refer to **LOO at the group level** (or leave-one-group-out CV, or LLO as you call it), or to **CV at the group level** (e.g. at the field level); I tried to clarify these differences in section 2
- **Block CV using k-means**: earliest reference may be Russ & Brenning (2010), I added it to section 2 <https://link.springer.com/chapter/10.1007/978-3-642-14049-5_36>
- **Group-level CV**: Brenning et al. 2006 <https://www.zfl.uni-bonn.de/research/earsel/special-interest-group-on-land-use/64-71_brenning.pdf> making explicit reference to spatial dependence as the reason for CV'ing spatial objects, not grid cells
  - Brenning, A., K. Kaden & S. Itzerott. 2006. Comparing classifiers for crop identification based on multitemporal Landsat TM/ETM data. In M. Braun (eds.), Proceedings, Second Workshop of the EARSeL Special Interest Group on Remote Sensing of Land Use and Land Cover, Bonn, 28-30 September 2006, pp. 64-71.

**Comment by alexanderbrenning** [comment]
As for the names of partitioning methods in sperrorest, please refer to the help files, not just the function names:
- partition_factor: help file calls it "leave-one-factor-out cross-validation" (of course it should say "level" not "factor")
- spatial LOO is implemented in partition_disc: "radius < 0 does leave-one-out resampling with an optional buffer", reference is Brenning 2005; partition_loo is just a special case of partition_disc, so partition_loo also implements spatial LOO

**Comment by pat-s** [comment]
Thanks!

> Predefined grouping is not a very precise concept, as it may refer to LOO at the group level (or leave-one-group-out CV, or LLO as you call it), or to CV at the group level (e.g. at the field level); I tried to clarify these differences in section 2

There are many different terminologies around for this approach. I think it would be good to find an overarching one which suits us. As LLO is specific to Hanna's CAST method, we could go with LOGO (leave one group out).
I agree that the term "predefined grouping" might not be ideal.

> As for the names of partitioning methods in sperrorest, please refer to the help files, not just the function names:

Thanks. So far I did not implement `partition_loo()` on purpose since AFAICS it would be identical to `spcv_buffer()` (LOO + buffer).

**Comment by pat-s** [comment]
Added Brenning et al. 2006 and renamed to group-level CV.

**Comment by pat-s** [comment]
I've rewritten the headers and implemented all mentioned refs.

The differentiation is now between "Group Level" CV and "custom CV" (aka predefined).
`sperrorest::partition_factor_cv()` is not implemented since it should be the same as LLO.

**Comment by pat-s** [comment]
Should be better/ok now, please re-open if you think there are still references missing.
