### ISSUE TITLE
Add more introductory information about autocorrelation

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatiotempcv#108]
- including formulas
- explain why custom resampling methods are needed and important in the first place

**Comment by alexanderbrenning** [comment]
Wrote a proposed new intro that motivates spatial resampling from a spatial prediction perspective, not so much from an autocorrelation perspective, which can be misleading. Important message: The needed spatial (or spatio-temporal) resampling design is as much a function of the structure of the prediction task as it is a function of the structure of the data itself, i.e. the autocorrelation (in whatever sense). But it's not the purpose of this paper to tell the reader what to do, but to provide a framework for whatever they want deem necessary.

Next on my list, the more formal section.

**Comment by pat-s** [comment]
closing in favor of #125
