### ISSUE TITLE
Expand Table listing all resampling methods 

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatiotempcv#110]
- [x] add some use cases for each method
- [x] list more implementations for each method (eventually also in other languages?)

Also consider to move methods operating in the feature space into a distinct group, e.g.:

- spatial
- spatiotemporal
- feature space

**Comment by pat-s** [comment]
![image](https://user-images.githubusercontent.com/8430564/116821763-74923c80-ab7b-11eb-842b-226244ed95b4.png)

@alexanderbrenning What is your opinion on this structuring?

**Comment by alexanderbrenning** [comment]
What about temporal CV? Spatial may not be necessary for all spatiotemporal tasks, especially in forecasting. Maybe a link to mlr3forecasting would be appropriate (in the text), but does mlr3forecasting handle spatial time series, e.g. data cubes? I suppose researchers would more likely look for this in this package.

Also, under spatial (or as a separate type) it would be good to include partitioning and resampling based on predefined groups, which may arise from the sampling design (multilevel sampling) or from the structure of the data (e.g., agricultural fields as groups of grid cells). This is, from an algorithmic perspective, implicitly spatial, not explicitly spatial, but it is spatial from a domain perspective.

Perhaps additional line like this (using pseudo-Markdown notation):

Factor | Grouping | sperrorest | "cv_???"^[in package \pkg{mlr3}] | [2]

Remember that there are two types of resampling based on factors, in sperrorest they are called partition_factor and partition_factor_cv where partition_factor is basically leave-one-level-out CV, and partition_factor_cv performs ordinary CV at the level of factor levels, i.e. objects.

Literature could be displayed using numeric references that are resolved in a table footnote, e.g. [1-2], and the footnote says e.g. [1] Brenning (2012), [2] Pena & Brenning (2015) etc.

**Comment by pat-s** [comment]
> What about temporal CV? Spatial may not be necessary for all spatiotemporal tasks, especially in forecasting. Maybe a link to mlr3forecasting would be appropriate (in the text), but does mlr3forecasting handle spatial time series, e.g. data cubes? I suppose researchers would more likely look for this in this package.

It is on the list (see #62) and there is one "moving-window" method in mlr3forecasting which will likely move into {mlr3spatiotempcv}.
{mlr3forecasting} is quite basic and not really ready for use - also we are discussing to rename it to {mlr3temporal}, containing only learners and measures.

> Also, under spatial (or as a separate type) it would be good to include partitioning and resampling based on predefined groups, which may arise from the sampling design (multilevel sampling) or from the structure of the data (e.g., agricultural fields as groups of grid cells). This is, from an algorithmic perspective, implicitly spatial, not explicitly spatial, but it is spatial from a domain perspective.

Yes, predefined resampling based on groups (leave-one-level-out CV) is planned to live directly in {mlr3} (no issue yet, just internal discussions) cc @mllg .
I've started here in #123 but this won't be continued.
`partition_factor_cv` based on flexible groups is already supported via the `"groups"` column role in {mlr3}.
It is already documented in some places but should be made clearer.

> Literature could be displayed using numeric references that are resolved in a table footnote, e.g. [1-2], and the footnote says e.g. [1] Brenning (2012), [2] Pena & Brenning (2015) etc.

This might be a solution, yes! Given that the citation style by JSS enforces author-year citations, we might need to find a workaround - a caption below the table referencing to numeric references in the table sounds good.

**Comment by pat-s** [comment]
## Literature research 

Number of occurrences in literature:

- spatial block: 25
- env block: 1
- buffering: 2
- spatial disc: FIXME
- spatial tiles: FIXME
- spatial coords: FIXME
- LLTO: FIXME
- CLUTO: FIXME

**Comment by pat-s** [comment]
@alexanderbrenning 

Here is the result. I've selected three references for each method (if there were three available). Do you have suggestions to further improve the table or do you think it is sufficient?

The refs are cited in footnotes on the respective page.

![image](https://user-images.githubusercontent.com/8430564/118954357-fa74fc80-b95d-11eb-8371-b9b409e332e1.png)

**Comment by pat-s** [comment]
Closing due to no response (assuming its okay now) - feel free to re-open if there are still open points to discuss :)
