### ISSUE TITLE
`.$folds()` of all Repeated* classes returns wrong fold number

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatiotempcv#120]
``` r
library(mlr3spatiotempcv)
library(mlr3)
rsp <- rsmp("repeated_spcv_coords", folds = 3, repeats = 5)
rsp$instantiate(tsk("ecuador"))

# should return 3
rsp$folds(6)
#> [1] 1
```

<sup>Created on 2021-04-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

This is because in https://github.com/mlr-org/mlr3spatiotempcv/blob/b9ded4ac098655dc00c300b48426bd6d4cd0a97a/R/ResamplingRepeatedSpCVCoords.R#L54 `%%` is used whereas it should be `%/%`.

But there is more to it - I think the method should look like

```r
    folds = function(iters) {
      iters = assert_integerish(iters, any.missing = FALSE, coerce = TRUE)
      n_folds = ((self$iters - 1L) %/% as.integer(self$param_set$values$repeats)) + 1L

      if (all(iters <= n_folds)) {
        return(iters)
      } else {
        # modify all entries which are > n_folds
        iters[which(iters > n_folds)] = iters[which(iters > n_folds)] - n_folds
        return(iters)
      }
    }
```

**Comment by pat-s** [comment]
@mllg I think this also applies to {mlr3}

I got a fix already (see OP); can open a PR in {mlr3} if approved.

``` r
library(mlr3)

task <- tsk("penguins")
task$filter(1:10)

# Instantiate Resampling
rrcv <- rsmp("repeated_cv", repeats = 2, folds = 3)
rrcv$instantiate(task)
rrcv$iters
#> [1] 6

# should be 1 2 3 1 2 3
rrcv$folds(1:6)
#> [1] 1 2 1 2 1 2
```

<sup>Created on 2021-04-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by pat-s** [comment]
ping @mllg

**Comment by pat-s** [comment]
@mllg I consider this still as "High" prio - also in {mlr3}. Before I do a PR a confirmation from your side would be appreciated though.

**Comment by mllg** [comment]
> @mllg I consider this still as "High" prio - also in {mlr3}. Before I do a PR a confirmation from your side would be appreciated though.

Bug fixes are always appreciated, and this is clearly a bug. https://github.com/mlr-org/mlr3/pull/643 should fix it.

**Comment by pat-s** [comment]
Thanks. If [`4fd985e` (#643)](https://github.com/mlr-org/mlr3/pull/643/commits/4fd985ebec5c8f4da7a19e65a0257b829fafdfcc) was sufficient then I've spent way too much time for my complicated workaround 😆

**Comment by mllg** [comment]
> Thanks. If [`4fd985e` (#643)](https://github.com/mlr-org/mlr3/pull/643/commits/4fd985ebec5c8f4da7a19e65a0257b829fafdfcc) was sufficient then I've spent way too much time for my complicated workaround laughing

I hope so :)
