### ISSUE TITLE
Write formal introduction to CV and spatial / structured variants

### ISSUE THREAD

**Issue by alexanderbrenning** [mlr-org/mlr3spatiotempcv#124]
write a brief intro using proper mathematical notation

**Comment by alexanderbrenning** [comment]
Still need to write...

- one paragraph in section 2 covering spCV with spatial partitioning
- one paragraph on temporal / spatiotemporal partitioning

**Comment by alexanderbrenning** [comment]
Make sure that terminology is consistent throughout the manuscript (and with the R package), e.g. 'environmental CV', 'LOO with buffer' etc.

**Comment by pat-s** [comment]
AFAIK this has been implemented 👍 Feel free to re-open if still valid.
