### ISSUE TITLE
mlr3spatiotempcv within mlr3 object model

### ISSUE THREAD

**Issue by alexanderbrenning** [mlr-org/mlr3spatiotempcv#126]
Section 3 could use *one* additional paragraph outlining mlr3spatiotempcv's place in the mlr3 object hierarchy. mlr3 is object-oriented, so what is the name and basic structure of object classes for partitioning / validation, are mlr3spatiotempcv classes a subclass with coordinates or what, how does this relate to established spatial object hierarchies as in sf or sp. This shouldn't be too detailed and technical, but the reader should know if and how it integrates into established object hierarchies within mlr3 and outside of it in the geospatial world. This will also create a smoother transition into the at times very technical sections that follow, which talk about methods of unspecified object classes within an unspecified object hierarchy. 
@pat-s do you want to give it a try?

**Comment by alexanderbrenning** [comment]
I drafted a paragraph (two, actually)

**Comment by pat-s** [comment]
Thanks! I agree this could be a good addition.

I'll continue/reply on your draft in the next days.

**Comment by pat-s** [comment]
LGTM so far, please reopen if you think something is still missing.
