### ISSUE TITLE
2D+time versus 3D

### ISSUE THREAD

**Issue by alexanderbrenning** [mlr-org/mlr3spatiotempcv#127]
## Issue

3D space as e.g. required by geophysists, atmospheric scientists, materials scientists or astronomers is probably not on your agenda for mlr3spatiotempcv. (Note that the third dimension in the geosciences is not just yet another dimension, it is usually quite different from x/y and t).

## To do

Make sure that the abstract, intro and background (and perhaps discussion) use precise wording that doesn't suggest that 3D space is being covered. Add 1-2 references to ML in 3D geosciences or 3d+time geosciences. I have some leads I can follow.

**Comment by alexanderbrenning** [comment]
This relates to #62

**Comment by pat-s** [comment]
Thanks. For now I think spatiotemp is enough. You're right that we should make clear what 3D means in this package/paper to avoid confusion.

"space" could either be seen as 1D or 2D depending on the context and using 2D+time might also be a valid nomenclature.

**Comment by pat-s** [comment]
Currently 3D only appears once (in the context of the `plot3D` argument in `autoplot()` and I explicitly added that it means space + time.

We could add more content to 3D in general but I am also not fully sure if this is really needed.

**Comment by pat-s** [comment]
Using 2D+time multiple times now in the manuscript.
