### ISSUE TITLE
Reference handling in paper

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatiotempcv#129]
@alexanderbrenning 

I've fixed all broken references in the manuscript (> 10).
The Rmd compiles even though the references are not found (this is both a feature and a bug I'd say).

When you add references by hand into `paper.bib`, this becomes troublesome for me because I am auto-updating paper.bib from my Zotero integration.
If this is done, it deletes your manual additions every time.

Would it be ok/possible for you to make use of the shared zotero library I shared with you some weeks ago?
If you input a reference there, it can update your local `.bib` file and you can then commit the changes.
This way, I will also directly have the same references on my machine.

Let me know if this needs more introduction/showcasing or if you would prefer another way of reference handling.

**Comment by pat-s** [comment]
In more recent versions of RStudio there is also a Zotero integration built-in (in the visual editor).

Especially when collaborating, using Zotero for a shared bibliography seems very beneficial and has the potential to save a lot of time :)

**Comment by alexanderbrenning** [comment]
OK. Thanks.
