### ISSUE TITLE
Spatiotemporal CV in Python

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatiotempcv#133]
[Overview issue]

- [spacv](https://github.com/SamComber/spacv) 
	- Still maintained?
    - h-blocking (= spatial block) + buffer support
    - `UserDefinedSCV`
    - `BaseSpatialCV` = k-means
    - Spatial Leave One Out (SLOO)
    - Rabinowicz' bias-corrected CV measure (?)
    - Area of applicability for spatial prediction
    - "Most fundamentally, it is the only Python library solely dedicated to spatial cross-validation and predictive methods."

- [verde](https://github.com/fatiando/verde)
  - spatial pred but no spatial CV

- [towardsdatascience blog post](https://towardsdatascience.com/spatial-cross-validation-using-scikit-learn-74cb8ffe0ab9) doing a k-means clustering manually

- [Pyspatialml](https://github.com/stevenpawley/Pyspatialml) which is a new project aiming to solve data preprocessing, CV and prediction for scikit-learn. Shows a manual k-means clustering on coords in its README

**Comment by pat-s** [comment]
We could add a paragraph into the paper discussing the current state of spatiotemporal resampling methods in other languages? @alexanderbrenning

**Comment by alexanderbrenning** [comment]
added sentence to Intro mentioning spacv

**Comment by pat-s** [comment]
Mentioned in the README and in the paper now.
