### ISSUE TITLE
Coherent terminology for partitioning and CV techniques

### ISSUE THREAD

**Issue by alexanderbrenning** [mlr-org/mlr3spatiotempcv#147]
There is still no consistent terminology for naming the partitioning and resampling techniques. Let me unload my frustration first before I propose a coherent system.

This is what's wrong:
1. Table 1 and Sections 4.1.2.1 and 4.1.2.2 fail to highlight the fundamental difference between *resampling at the group/block/cluster level* and *leaving one group/block/cluster out* at a time. I had tried to emphasize this fundamental difference in Section 2...
2. The *LLO/LLTO/LTO terminology is misleading* and flawed and should therefore *be abandoned*. "Leave-one-[...-]out" resampling / CV has long been established in the literature (for decades), and I am only aware of its use in conjunction with the number ONE. I realized only now that LLO (etc.) in the sense of Meyer's paper really means "leave one or many locations out" - the singular word is misleading as it suggests that only one location is left out, and therefore LLO resampling is either leave-one-location-out resampling ($k = n$-fold CV) or simply CV at the location level ($k < n$ folds). 
3. The package and manuscript promise to provide an overarching, *coherent terminology* and toolbox, but they currently fail to do so because ultimately each interfaced package's/paper's terminology is just being copied. This is confusing. E.g., rectangular blocks and tiles are geometrically the same. But `blockCV` performs resampling at the block level, and `partition_tiles` in `sperrorest` performs leave-one-block-out resampling.
4. Technically, *buffering* is an approach that can be applied to any selection of a test set, regardless of whether it consists of one point, one group/block/cluster, or a collection of groups/blocks/cluster. It is not a resampling method, it is an *attribute* of resampling methods, and should therefore not be a row in Table 1. E.g., `partition_disc` in `sperrorest` technically implements circular blocks/groups with an optional buffer. `partition_loo` in `sperrorest` and, as far as I know, the buffering method in `blockCV` implement leave-one-out CV with a buffer, also known as spatial LOO.
5. *Custom* resampling should be renamed - the name doesn't tell the user whether it is a leave-one-custom-object-out technique or whether it arranges the custom objects into $k$ groups of custom objects (custom-object-level CV), where each custom object may contain multiple observations.

The following terminology should therefore be adopted:
1. Distinguish between partitioning, resampling, and CV more carefully (but I didn't do so in my rant above); they are not the same. Use "partitioning" only in the $k$-fold CV sense, i.e. there can only be $k$ partitions (and $k=n$ is allowed).
2. Groups/blocks/clusters/sites are all just grouping structures that differ in how they are derived from the data's inherent structure or sampling design (e.g., site, agricultural field, or cluster in the sense of clustered sampling design), or constructed algorithmically from spatially unstructured data ($k$-means clustering, rectangular blocks, discs). Without loss of generality, we may just pick one of these fours terms, e.g. *blocks*, to refer to any of the four types of grouping. Rectangular blocks are just a special type of blocks, as are polygonal ones etc.
3. Resampling for CV can be done with the $n$ individual observations, or with the $n_z$ blocks (which I refer to as zones in section 2). Refer to these as (non-spatial) *CV* and as *block-level CV*, respectively. Add the attribute "*buffered*" whenever a buffer distance >0 is applied.
4. LOO-CV can also be done at the level of individual observations, or at the level of blocks[/groups/sites/time series/...]. Refer to this as *leave-one-block-out CV* (LOBO-CV), where blocks, again, can be constructed in different ways, which may give rise to LOGO-CV, LOSO-CV, and I'm sure there's also a loco CV. If a distance buffer is applied, call it a buffered LOBO-CV.
5. Instead of custom CV, we need to distinguish between LOBO-CV of user-defined blocks (e.g., provided as a shapefile or as an attribute of type factor), and block-level CV with user-defined blocks.

Footnotes on specific methods / issues:
1. Note that the disc-based method is, strictly speaking, not a CV in the traditional sense since it is not based on partitioning the sample. I'm glad that no-one ever noticed ;-) I think the term 'leave-one-disc-out CV', which I used in the `sperrorest` helpfile, is nevertheless still justified.
2. LLTO in the sense of Meyer seems to be a bit hard to characterize. It is technically not based on a partitioning in (space, time), but on two independent partitionings of space and time. The partitioning in space is a random partitioning, not strictly speaking a spatial partitioning. In the case where one space-time observation is left out (I think that's an option?), it becomes a LOO-CV with buffer where an interesting distance metric is used that treats spatial and temporal dimensions separately. When multiple locations and multiple time points are left out, it becomes sort of a buffered block resampling, but it's more like a collection of individual sheets (in space) or threads (in time) that form the test set, and the interesting distance metric is applied to define the buffers.

**Comment by pat-s** [comment]
This should have been made clear in the manuscript meanwhile and discussed in many discussions in the meantime. Thanks for raising!
