### ISSUE TITLE
Acceptable values for folds argument in checkerboard resampling

### ISSUE THREAD

**Issue by alexanderbrenning** [mlr-org/mlr3spatiotempcv#149]
In the manuscript, I noticed that checkerboard resampling is used with argument `folds = 5` (code chunk `block-checkerboard`). Looking at the corresponding figure, checkerboard resampling is two-fold by definition (black and white fields on the checkerboard, of course). The `folds` argument should therefore only accept values 1 and 2; there's no "place" for additional folds, which are technically subsets (or in other words, for `folds` > 2, the test set should technically be an empty set).
In the manuscript in particular, the argument `folds = 5` should also be avoided for pedagogical reasons as readers might wonder how folds 3-5 would look like.

Other resampling techniques will have similar constraints, e.g. in custom CV (based on a factor variable), `folds` must be <= `nlevels(factor_variable)`, or in LLO, <= #locations, but I haven't checked if these constraints are checked.

**Comment by pat-s** [comment]
Thanks, that's a good catch!

I think throwing a warning that `folds` will have no effect when `selection = "checkerboard"` and hinting that the outcome will always be two-fold could be an appropriate solution. 

In the background this is already done,, there are only two folds created in this scenario.

Similar, `autoplot()` should throw a warning when a fold ID is requested which is > available folds.
Currently it returns a plot but without train/test separation.

**Comment by pat-s** [comment]
`custom_cv` is not affected by this as there is no `folds` argument and the number of folds is directly inferred by the factor levels.

The general problem only applies to methods which have both a custom partitioning logic (which possibly comes with an upper limit) and a folds argument for post-hoc aggregation.
