### ISSUE TITLE
linnenbrink2023 reference broken in mlr3spatiotempcv vignette

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3spatiotempcv#235]
The citation for KNNDM is broken in the vignette. This is because linnenbrink2023 is in the R/bibentries.R file, but not in the bib file used by the vignette.

See the table at the bottom of https://mlr3spatiotempcv.mlr-org.com/dev/articles/mlr3spatiotempcv.html:

![image](https://github.com/mlr-org/mlr3spatiotempcv/assets/15801081/5ce5c6c2-6527-4220-8b34-b24d0eb89102)

**Comment by pat-s** [comment]
thanks!
