### ISSUE TITLE
Coordinates in the mlr3 Task object

### ISSUE THREAD

**Issue by mafla** [mlr-org/mlr3spatiotempcv#24]
Hi, I am trying to generate a task with my own data as it was shown in some tutorials for mlr. I do some random data and have a data.frame with coordinates. So that when I define the TaskRegr$new( .... , coordinates = coords) which results in:

Error in .subset2(public_bind_env, "initialize")(...) : 
  unused argument (coordinates = coords)

adding coordinates manually to the task does not work either. It would be great to have here a full example from some raw data of a regression problem where one wants to predict y from X and has lat, lon coords to consider in the CV.

**Comment by pat-s** [comment]
{mlr3spatiotempcv} comes with with its own child class for tasks, i.e. 

- [TaskRegrST](https://mlr3spatiotempcv.mlr-org.com/reference/TaskRegrST.html) 
- [TaskClassifST](https://mlr3spatiotempcv.mlr-org.com/reference/TaskClassifST.html)

The package is still maturing and we will add a section to the manual hopefully soon.
