### ISSUE TITLE
misleading description of coordinates type in TaskRegrST

### ISSUE THREAD

**Issue by jannes-m** [mlr-org/mlr3spatiotempcv#25]
Dear spatio-temporal guys,
first of all, thanks for providing spatial cv via *mlr3*!!!  I am playing around a bit with *mlr3spatiotempcv*. In the help file of `TaskRegrST()`, it says that `coordinates` should be a `data.frame` when it fact, you need to provide a character string indicating the column names of the coordinates found in the `backend`. A spatio-temporal example would be rather helpful indeed (as already pointed out in #22 and #24). If I can be of any help re the example, pls let me know.

**Comment by pat-s** [comment]
Thanks. Indeed, some clean up is needed here. We also need to adapt to the latest notation in the upstream mlr3 resampling methods. Thanks for mentioning/pushing :)
