### ISSUE TITLE
Support resampling method based on predefined spatiotemporal groups

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatiotempcv#38]
Just as `CAST::CreateSpacetimeFolds()` does.

I am not sure if this approach can work with all currently implemented spatial sampling methods.
Even if not, we should support exactly this way of creating resamplings since some people already asked me exactly for this.
@HannaMeyer Is there a dedicated name for your method? If not, do you want to make a proposal? :)
You can have a look at the current names of the other methods in the README.

It seems that @jannes-m has added temporal extension support for `spcv-coords` already.
Let's have a look how this works in detail.

**Comment by HannaMeyer** [comment]
No dedicated name yet. Although the current function name assumes so it's not even limited to spatio-temporal dependencies but can be used for data with any one or two dependencies. The function is only doing the resampling based on the pre-defined groups of dependencies (e.g. spatial blocks as well as the month of the year).
So "user defined CV" is my best suggestion.

**Comment by jannes-m** [comment]
What I will add is a very slight modification of the k-means spatial resampling. Just as background information: in Peru I have visited the same 50 plots in four different years (2011, 2012, 2016, 2017). Hence, when doing the spatial resampling, we have made sure that all observations of one plot were put jointly into the testing (or training) dataset. And as far as I remember, this is exactly, what @HannaMeyer also implemented, right?

**Comment by HannaMeyer** [comment]
yes. In CreateSpaceTimeFolds you would use something like a plot-ID as grouping variable and then it would do the same: all observations of one (or more, depending on the number of folds) plot jointly in one fold.

**Comment by jannes-m** [comment]
Ok, I have adapted `ResamplingSpCVCoords$.sample()` in such a way that it also accepts a group. In the example below, I have created a dataset in which the ID column and the coordinates are repeated four times (i.e., I simulated my Peru dataset). As I said before, this is only a very slight modification of the kmeans-approach. @pat-s pls let me know if you want me to implement this approach at all. And if so, if as a new method or as an argument of `ResamplingSpCVCoords`.


``` r
library("data.table")
set.seed(123)
# simulate 50 plots that have been re-visited four times in different years
ids = rep(1:50, 4)
# coordinates
coords = seq(from = -20, to = 20, by = 0.01)
# repeat x- and y-coordinates four times
coords = data.table(x = rep(sample(coords, 50), 4), 
                    y = rep(sample(coords, 50), 4))

# adjust ResamplingSpCVCoords$.sample

.sample_by_group = function(ids, coords, group) {
  # remember how many groups there are
  n_gr = length(group) / uniqueN(group)
  coords = cbind(coords, "group" = group)
  # just use unique ids for the spatial resampling
  un = coords[!duplicated(group)]
  # delete the grouping column again
  un[, group := NULL]
  # inds = kmeans(coords, centers = self$param_set$values$folds)
  # kmeans clustering
  inds = kmeans(un, centers = 5)
  # repeat the cluster classes as many times as there are groups 
  cluster = rep(inds$cluster, n_gr)
  
  data.table(
    row_id = ids,
    fold = cluster,
    key = "fold"
  )
}

dt = .sample_by_group(ids = ids, coords = coords, group = ids)  
# visualize the output
plot(coords[, .(x, y)])
points(coords[dt[fold == 1, row_id]], col = "blue", pch = 16)
points(coords[dt[fold == 2, row_id]], col = "red", pch = 16)
points(coords[dt[fold == 3, row_id]], col = "green", pch = 16)
points(coords[dt[fold == 4, row_id]], col = "yellow", pch = 16)
points(coords[dt[fold == 5, row_id]], col = "pink", pch = 16)
```

![](https://i.imgur.com/FS56Xbx.png)

``` r

# and just to verify that each coordinate has been sampled several times
dt[, .N, by = "fold"]
#>    fold  N
#> 1:    1 36
#> 2:    2 48
#> 3:    3 40
#> 4:    4 48
#> 5:    5 28
```

<sup>Created on 2020-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by pat-s** [comment]
Thanks!

So in summary:

- Without the group here we would allow kmeans to pull in any obs into the cluster
- With the group, we restrict each cluster to only consist of one group; this may cause some clusters to consist of substantially more/less observations. Correct?

By this one accounts for the temporal aspect in the data by preferring temporal grouping over spatial grouping (since kmeans is stripped to not include all obs it would be naturally due to the grouping).

Since we are short on names anyways and I would like to keep the amount of methods small, I'd suggest to add it as an argument. The same could go into `SpCVEnv` then because this method also used clustering under the hood. 

Not sure if it would work with the "block" approach but maybe this is a different issue for now.

Regarding implementation we should make use of the [`group` column](https://mlr3.mlr-org.com/dev/reference/Resampling.html#grouping-blocking) role in class `Task`.
And we should highlight this option explicitly in the table in the README with a TRUE/FALSE like column stating whether this method is capable of dealing with temporal data.

**Comment by jannes-m** [comment]
In fact, we should make sure that as soon as one plot is selected for the training dataset, all other observations from the same plot (only from other years) should be put also into the training dataset. However, observations from different years but from the same location, of course, share the same coordinates. Hence, they would be automatically put into the same dataset (training or testing) by the kmeans clustering. Right now, I am bit confused or just sleep-deprived, @HannaMeyer, can you pls help me out, what am I missing?

**Comment by HannaMeyer** [comment]
If we have two dependencies (space and time) and want to do CV with independent time and independent space at the same time I think we cannot use all data for cross validation but have to waste some. See the figure attached. Other suggestions are welcome!
[cv.pdf](https://github.com/mlr-org/mlr3spatiotempcv/files/4142419/cv.pdf)

**Comment by pat-s** [comment]
Essentially we're doing a clustering in a three-dimensional space, aren't we? For spatial only its 2-dimensional.

Shouldn't kmeans be capable to do this by just passing a 3-dimensional numeric matrix?

Maybe we make our lives easier if we use a 3D plotting method to visualize the resulting 3D clustering?
The clustering should account naturally for both space and time and we might not even need to remove observations?

**Comment by jannes-m** [comment]
Excellent figure, @HannaMeyer, closed the gap in my head. @pat-s I will experiment with your suggestion and if this doesn't work, I will implement approach as proposed in Hannah's figure (llto-cv).

**Comment by jannes-m** [comment]
I have played around a bit, and the kmeans stuff does not work for x, y and time. So I think the most appropriate solution would be to implement Hanna's procedure. But of course, we can Alex what he thinks: is it sufficient to just leave out location while making sure that we use all temporal observations of one plot for either testing or training (this is what the kmeans already is doing automatically) or should we also leave time out. Coming back to my Peruvian example (50 plots recorded 4 times in 2011, 2012, 2016 & 2017), we would have to do the spatial sampling, which already leaves out, say 10 plots. Then we would have to build the model based on the obs in 2012, 2016 and 2017 without the the 10 left out plots and test the model them on the 10 left out plots in 2011.

**Comment by pat-s** [comment]
If we use predefined groups, I am not sure if we can call it "clustering". Probably not?
See #51 for a different approach to conduct a three-dimensional clustering.

Anyhow, @HannaMeyer's method should also definitely go into the package!

@jannes-m approach seems to be a hybrid one (?): predefined temporal groups but clustering in the spatial domain.

It would also be great if we could have a three-dimensional visualization of space-time partitions since they are hard to imagine in a 2D space.

**Comment by jannes-m** [comment]
Hey @pat-s ,
forget about my approach, it's just a light version of Hanna's approach and in fact not very meaningful since the kmeans clustering is already automatically taking care of the temporal dimension (see also my previous comment and/or I'll better explain this in person), anyways, just forget about it. Hence, we should implement Hanna's approach. A long time ago, I already started to do so but not sure when I will find the time to finish it and if my coding corresponds to your mlr3 code guidelines.

**Comment by pat-s** [comment]
@jannes-m AFAIK Hanna is not using a clustering technique per so but uses a predefined grouping index?

Your technique would make use of `kmeans` and then add a fixed temporal group in addition (i.e. hybrid).

Anyhow, I made some major progress yesterday in #51 and hoping that this will become a new player in the game.

**Comment by jannes-m** [comment]
We would make use of kmeans and leave one timestamp out. Have a look at Hanna's figure which illustrates the concept nicely. You'll find in one of her previous comments.

**Comment by pat-s** [comment]
We now have the following spatio-temporal resampling methods

- `ResamplingSptCVCluto` 
- `ResamplingSptCVCstf`

@jannes-m Regarding the hybrid `kmeans` approach: AFAICS there the focus of reducing autocorrelation lies on the spatial domain while the temporal autocorrelation is only addressed by leaving "this one group" out. However, it cannot be determined how strong that effect is and if it would be better/necessary to leave maybe two timesteps out (or more/less).

So I think this hybrid approach would be hard to port to other use cases in a generic way that is easily justifiable. While this probably partly applies to any spatio-temporal resampling technique, the less subjective user decision need to be made when creating the clusters, the better.
