### ISSUE TITLE
make spatiotempcv compatible with other packages

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3spatiotempcv#45]
- Currently `mlr3spatiotempcv` overwrites `col_roles` and `row_roles` in [zzz.R](https://github.com/mlr-org/mlr3spatiotempcv/blob/master/R/zzz.R).
This makes it non-compatible with other packages, i.e. if I load a package that adds a different set of `col_roles`, those are overwritten by `mlr3spatiotempcv`. We should append instead of overwriting here.

- The fact that the `task_type` is non-unique after loading `mlr3spatiotempcv` leads to tiny problems in `mlr3pipelines`. We should discuss at a higher level how we expect packages in the `mlr3verse` to behave here, as it is not completely clear how things should work here.
We will fix find a work-around in `mlr3pipelines` for now.

**Comment by pat-s** [comment]
Ref https://github.com/mlr-org/mlr3/issues/470
