### ISSUE TITLE
Explore a three-dimensional clustering method

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3spatiotempcv#51]
To cluster in x, y and time.

Package [skmeans](https://cran.r-project.org/web/packages/skmeans/index.html) looks promising. 
Among other methods, it comes with an interface to [CLUTO](http://glaros.dtc.umn.edu/gkhome/cluto/cluto/overview), which seems to specifically address high-dimensional clustering in GIS applications.

**Comment by pat-s** [comment]
Sneak preview @hannameyer @jannes-m 

3D plotly viz

![newplot](https://user-images.githubusercontent.com/8430564/87451551-4d747980-c600-11ea-84f7-55e92cc07f5b.png)

**Comment by HannaMeyer** [comment]
That's great!!
