### ISSUE TITLE
Need for gap filling approach within mlr3spatiotempcv for time-series data

### ISSUE THREAD

**Issue by mohammadreza-sheykhmousa** [mlr-org/mlr3spatiotempcv#78]
Hi,

Can we have a gap filling approach within `mlr3spatiotempcv`?

Here are some examples of the problem and solutions for your reference:
[LINK1](https://gking.harvard.edu/amelia)
[LINK2](https://bg.copernicus.org/articles/10/4055/2013/bg-10-4055-2013.pdf)
[LINK3](https://www.sciencedirect.com/science/article/pii/S0924271614002512)

**Comment by pat-s** [comment]
I don't see how the methodology in the links relate to this package.

Filling gaps in time series data is a preprocessing task and hence should be covered as a pipelines (mlr3pipelines). Maybe it fits into {mlr3forecasting} but I've really just taken a coarse look.

**Comment by pat-s** [comment]
@mohammadreza-sheykhmousa Is there a reason why you almost never reply to my replies? Just wondering. Closing here then.

**Comment by mohammadreza-sheykhmousa** [comment]
Dear @pat-s I am sorry for the late reply and inconvenience I might caused. No there is no reason to that and actually I am very much fund of you guys at mlr3. Just two past weeks I was/am terribly busy with this gap filling approach for time series data for 20 years Landsat imagery for the  whole eu. 
- I do agree `mlr3pipelines` is a better fit. and I'll raise the issue there. 
- Technically speaking there some existing approaches approaches for gap filling data and specially for a huge stack of satellite imagery data as:
    - linear approaches like `mean`  (which is pretty lame approach)
    - `repeat last seen observation`
    - etc.
but a robust method for such a challenge is missing. That  is why I asked about develop/adopting an approach to address the challenge.

Best, Mo
